// frontendAngular/src/app/components/alert/alert.component.ts
import { Component, OnInit } from '@angular/core';
import { tipoAlerta } from 'src/app/enums/global-enums';
import { AlertasService } from 'src/app/services/alertas/alertas.service';

@Component({
  selector: 'app-alert',
  templateUrl: './alert.component.html',
  styleUrls: ['./alert.component.css']
})
export class AlertComponent implements OnInit {
  protected mensaje: String = '';
  protected titulo: String = 'Información';
  protected tipoAlerta: tipoAlerta = tipoAlerta.success;
  protected mostrar: Boolean = true;

  constructor(
    protected _alertasService: AlertasService
  ) { }

  ngOnInit(): void {
  }

  protected ocultar(){
    this._alertasService.mostrar = false;
    this._alertasService.titulo = '';
    this._alertasService.mensaje = '';
  }

}

<div *ngIf="_alertasService.mostrar" [class]="'alert alert-' + _alertasService.tipo + ' alert-dismissible fade show'" role="alert">
    <strong>{{ _alertasService.titulo }}</strong> {{ _alertasService.mensaje }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span (click)="ocultar()">&times;</span>
    </button>
</div>

// frontend-vue/src/components/alert/alert.vue
<template>
    <div v-if="mostrar" :class="'alert alert-' + tipo + ' ' + (isItem ? 'alertItem' : '') + ' alert-dismissible fade show'" role="alert">
        <label><strong>{{ titulo }}</strong> {{ mensaje }}</label>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" @click="cerrar">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</template>
    
<script>
    import alerta from './alert.js';
    export default alerta;
</script>

<style type="scss">
    @import './alert.scss';
</style>
