// frontend-react/src/components/grupoAlertas/grupoAlertas.jsx
import React from "react";
import { AlertComponent } from "../alerta/alert";
import './style.scss'

export const  GrupoAlertasComponent = (props) => {
    const { alertas } = props;

    return (
        <div className="grupoAlertasContainer">
            { alertas && alertas.map( (a, key) => {
                return <AlertComponent key={key} titulo={a.titulo} mensaje={a.mensaje} tipo={a.tipo} mostrar={true}/>
            })} 
        </div>
    );
}

// frontend-vue/src/components/grupoAlertas/grupoAlertas.vue
<template>
    <div class="grupoAlertasContainer" v-if="alertas.length > 0">        
        <Alert 
            v-for="(item, key) in alertas" 
            :key="key" 
            :titulo="item.titulo" 
            :mensaje="item.mensaje" 
            :tipo="item.tipo" 
            :isItem="true"
        />
    </div>
</template>

<script>
    import GrupoAlertas from './grupoAlertas.js';
    export default GrupoAlertas;
</script>

<style type="scss">
    @import './grupoAlertas.scss';
</style>
