// frontend-vue/src/views/backoffice/login/login.vue
<template>
    <div className="login-container">
        <GrupoAlertasComponent :alertas="alertas"/>
        <main className="d-flex w-100">
            <div className="container d-flex flex-column">
                <div className="row vh-100">
                    <div className="content-login col-sm-10 col-md-8 col-lg-6 mx-auto h-100">
                        <div className="d-table-cell align-middle login-form">

                            <div className="text-center mt-4">
                                <h1 className="h2">Bienvenido</h1>
                                <p className="lead">
                                Ingresa a tu cuenta para continuar
                                </p>
                            </div>

                            <div className="card">
                                <div className="card-body">
                                    <div className="m-sm-4">
                                        <form>
                                            <div className="mb-3">
                                                <label className="form-label" htmlFor="email">Email</label>
                                                <input className="form-control form-control-lg" type="email" id="email" placeholder="Ingresa tu email" v-model="email" @change="emailHandler"/>
                                            </div>
                                            <div className="mb-3">
                                                <label className="form-label" htmlFor="password">Contraseña</label>
                                                <input className="form-control form-control-lg" type="password" id="password" placeholder="Ingresa tu contraseña" v-model="password" @change="passwordHandler"/>
                                                <small>
                                                    <a href="index.html">¿Olvidastes tu contraseña?</a>
                                                </small>
                                            </div>
                                            <div>
                                                <label className="form-check" htmlFor="remember-me">
                                                    <input className="form-check-input" type="checkbox" value="remember-me" id="remember-me" v-model="remember" @keypress.enter="remenberChange"/>
                                                    <span className="form-check-label">
                                                        Recordarme la próxima ves
                                                    </span>
                                                </label>
                                            </div>
                                            <div className="text-center mt-3">
                                                <button
                                                    type="button"
                                                    className="btn btn-lg btn-primary"
                                                    @click="loginClick"
                                                >Ingresar
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</template>

<style lang="scss">
  @import './login.scss';
</style>

<script>
    import Login from './login.js';
    export default Login
</script>

// frontendAngular/src/app/pages/backoffice/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { LoginService } from '../../../services/login/login.service';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { TokenService } from '../../../services/token/token.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: [
    './login.component.css?',
    '../../../../assets/css/app.css'
  ]
})
export class LoginComponent implements OnInit {
  public form: FormGroup = new FormGroup({
    email: new FormControl('',[Validators.required, Validators.maxLength(150)]),
    password: new FormControl('', [Validators.required, Validators.maxLength(20)]),
    host: new FormControl(''),
    rememberMe: new FormControl(false)
  })

  constructor(
    private _loginService: LoginService,
    private _tokenServices: TokenService,
    private router: Router
  ) {

  }

  ngOnInit(): void {
    const token: string | null = this._tokenServices.resumeSession();
    if(token){
      this._loginService.refreshToken().subscribe({
        complete: () => {},
        error: e => this.errorHandler(e),
        next: (res: any) => {this.loginSuccess(res)}
      });
    }
  }

  public login(){
    this._loginService.login(this.form).subscribe({
      complete: () => { console.log('Login is complete') }, // completeHandler
      error: (e) => { this.errorHandler(e) },    // errorHandler
      next: (resp: any) => { this.loginSuccess(resp) },     // nextHandler
    })
  }

  private loginSuccess(resp: any){
    this._tokenServices.saveToken(resp.access_token, resp.refresh_token);
    this.router.navigate(['/admin']);
  }

  private errorHandler(error: any){
    console.log('ERROR',error);
  }
}

<div class="login-container">
<main class="d-flex w-100">
  <div class="container d-flex flex-column">
    <div class="row vh-100">
      <div class="content-login col-sm-10 col-md-8 col-lg-6 mx-auto h-100">
        <div class="d-table-cell align-middle login-form">

          <div class="text-center mt-4">
            <h1 class="h2">Bienvenido</h1>
            <p class="lead">
              Ingresa a tu cuenta para continuar
            </p>
          </div>

          <div class="card">
            <div class="card-body">
              <div class="m-sm-4">
                <form [formGroup]="form">
                  <div class="mb-3">
                    <label class="form-label" for="email">Email</label>
                    <input class="form-control form-control-lg" type="email" id="email" formControlName="email" placeholder="Ingresa tu email" />
                  </div>
                  <div class="mb-3">
                    <label class="form-label" for="password">Contraseña</label>
                    <input class="form-control form-control-lg" type="password" id="password" formControlName="password" placeholder="Ingresa tu contraseña" />
                    <small>
                      <a href="index.html">¿Olvidastes tu contraseña?</a>
                    </small>
                  </div>
                  <div>
                    <label class="form-check" for="remember-me">
          <input class="form-check-input" type="checkbox" value="remember-me" id="remember-me" formControlName="rememberMe" checked>
          <span class="form-check-label">
            Recordarme la próxima ves
          </span>
        </label>
                  </div>
                  <div class="text-center mt-3">
                    <button
                      [disabled]="form.invalid"
                      type="button"
                      (click)="login()"
                      class="btn btn-lg btn-primary"
                    >Ingresar</button>
                  </div>
                </form>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</main>
</div>
