// frontend-vue/src/views/backoffice/home/home.vue
<template>
    <div class="content-app">
        <AdminLeftMenu></AdminLeftMenu>
        <div class="mnu-is-open">
            Este es home.
        </div>
    </div>
</template>

<style type="scss">
    @import './home.scss';
</style>

<script>
    import AdminLeftMenu from '@/components/adminLeftMenu/adminLeftMenu.vue';

    export default {
        name: 'homePage',

        components:{
            AdminLeftMenu
        }
    }

</script>

// frontend-react/src/pages/backOffice/home/home.jsx
import React from 'react';
import { BackendLeftMenu } from '../../../components/backLeftMenu/backenLeftMenu';
import './style.scss';

export const HomePage = () => {

    return (
        <div className='content-app'>
            <BackendLeftMenu/>
            <div className='main-content'>
                Esta es la página principal de administración
            </div>
        </div>
    );
}
